### PR TITLE
Forked SEAIR

### LINKED ISSUE #18: Multiple infectivity rates
`metapop_model` does not allow for multiple infectivity rates for A and I compartments.

### PR DESCRIPTION
**Pull request by mehradans92**
Redefined the epidemiology model as a forked SEAIR in `Patient_zero.ipynb` and `NY_state_data_fitting.ipynb` notebook. beta `ParameterHypers` are now defined as a list with the length of number of infectious compartments.

### CODE REVIEW

**Comment by mehradans92** [comment]
Currently it runs ok by considering `n_infectious_compartments=1` in `maxentep.MetaParameterJoint`. But raises this error for higher values:
```InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-20-4624678b8c2e> in <module>
----> 1 v = param_model.sample(100)
      2 beta_dist = v[3]
      3 beta_dist

c:\users\user\desktop\research\covid-19\modeling\package\maxentep\maxentep\metapop_model.py in sample(self, N, return_joint)
    147 
    148     def sample(self, N, return_joint=False):
--> 149         joint = self(tf.constant([1.]))
    150         if type(joint) != list:
    151             joint = [joint]
InvalidArgumentError: Invalid parameters [Op:StatelessParameterizedTruncatedNormal]```

**Comment by whitead** [comment]
We currently have a distribution for beta. Do you think it might be smarter to just sample from that distribution n_infectious_compartments times? Having to list hyperparameters for beta_1, beta_2, beta_3, seems to require too much prior information to me.

**Comment by whitead** [comment]
Could your error be coming from the previous change? It seems to involve a truncated normal, which was in your other PR

**Comment by mehradans92** [comment]
Thanks for your review @whitead. I thought about using the same distribution again but that would not allow for choosing a different mean, max, min and var for the second distribution, right?

**Comment by whitead** [comment]
@mehradans92 no, not for the prior. Do we know for C19 the two different betas? If you want to achieve though you can instead make `beta_var` a list instead of individual `beta_var_1`, `beta_var_2`, etc. to avoid code duplication.

**Comment by mehradans92** [comment]
@whitead I will update the list implementation.

**Comment by whitead** [comment]
@mehradans92 Does it make sense to move your metrics (traj KL) out of the notebook?

**Comment by mehradans92** [comment]
Thanks for your review @whitead. Moved loss functions to `utils.py`.

**Comment by whitead** [comment]
I'll approve PR, but we should work out that KL divergence formula in latex for the paper. I don't quite follow it right now

**Review by whitead — APPROVED** [review]

**Pull request merged**
